sherlock:
  wait_time_next_check: 3600
  slack:
    token: 12345token
    username: my-bot
    iconEmoji: ":helmet_with_white_cross:"
    channel: "my-channel"
  hosts:
    - hostname: host01.test.com
      port:
        - 80
        - 443
    - hostname: host02.test.com
      port:
        - 22